Sigor/config/routes.rb
Sigor::Application.routes.draw do
  resources :anteproyectos

  get "home/index"

  root to: "home#index"

  devise_for :users

end

Sigor/app/models/anteproyecto.rb
class Anteproyecto < ActiveRecord::Base
  belongs_to :user
end

Sigor/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :anteproyectos
end

Sigor/app/controllers/anteproyectos_controller.rb
class AnteproyectosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_anteproyecto, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if current_user.TipoUsuario == "Jefe V.P"
  @anteproyectos = Anteproyecto.all
elsif current_user.TipoUsuario == "M.Academia"
@anteproyectos = Anteproyecto.all
else
  @anteproyectos = Anteproyecto.where(user_id: current_user.id)
    respond_with(@anteproyectos)
  end
end

  def show
    respond_with(@anteproyecto)
  end

  def new
    @anteproyecto = current_user.anteproyectos.build
    respond_with(@anteproyecto)
  end

  def edit
  end

  def create
    @anteproyecto =current_user.anteproyectos.build(anteproyecto_params)
    @anteproyecto.update(:Estatus => "Enviado")
    @anteproyecto.save
    respond_with(@anteproyecto)
  end

  def update
    @anteproyecto.update(anteproyecto_params)
    if current_user.TipoUsuario == "Jefe V.P"
    @anteproyecto.update(:Estatus => "En revisión")
    end
    if current_user.TipoUsuario == "M.Academia"
    @anteproyecto.update(:Estatus => "Aprobado")
    end
    respond_with(@anteproyecto)
  end

  def destroy
    @anteproyecto.destroy
    respond_with(@anteproyecto)
  end

  private
    def set_anteproyecto
      @anteproyecto = Anteproyecto.find(params[:id])
    end

    def anteproyecto_params
      params.require(:anteproyecto).permit(:Nombre, :Objetivo, :Justificacion, :Cronograma, :DescripcionActividades, :NombreEmp, :DireccionEmp, :TelefonoEmp, :Comentarios, :Estatus, :user_id)
    end
end

Sigor/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:Nombre, :Promedio, :PlanEstudios,:NoControl, :Carrera, :TipoUsuario, :email, :password,  :current_password) }
     devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:Nombre, :Promedio, :PlanEstudios,:NoControl, :Carrera, :TipoUsuario, :email, :password,  :current_password) }
  end

end

Sigor/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

Sigor/app/helpers/anteproyectos_helper.rb
module AnteproyectosHelper
end

Sigor/app/helpers/application_helper.rb
module ApplicationHelper
end

Sigor/app/helpers/home_helper.rb
module HomeHelper
end

Sigor/app/views/anteproyectos/_form.html.erb
<%= form_for(@anteproyecto) do |f| %>
  <% if @anteproyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anteproyecto.errors.count, "error") %> prohibited this anteproyecto from being saved:</h2>

      <ul>
      <% @anteproyecto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Objetivo %><br>
    <%= f.text_field :Objetivo %>
  </div>
  <div class="field">
    <%= f.label :Justificacion %><br>
    <%= f.text_field :Justificacion %>
  </div>
  <div class="field">
    <%= f.label :Cronograma %><br>
    <%= f.text_field :Cronograma %>
  </div>
  <div class="field">
    <%= f.label :DescripcionActividades %><br>
    <%= f.text_field :DescripcionActividades %>
  </div>
  <div class="field">
    <%= f.label :NombreEmp %><br>
    <%= f.text_field :NombreEmp %>
  </div>
  <div class="field">
    <%= f.label :DireccionEmp %><br>
    <%= f.text_field :DireccionEmp %>
  </div>
  <div class="field">
    <%= f.label :TelefonoEmp %><br>
    <%= f.text_field :TelefonoEmp %>
  </div>
  <div class="field">
    <%= f.label :Comentarios %><br>
    <%= f.text_field :Comentarios %>
  </div>
  <div class="field">
    <%= f.label :Estatus %><br>
    <%= f.text_field :Estatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Sigor/app/views/anteproyectos/edit.html.erb
<h1>Editing anteproyecto</h1>

<%= render 'form' %>

<%= link_to 'Show', @anteproyecto %> |
<%= link_to 'Back', anteproyectos_path %>

Sigor/app/views/anteproyectos/index.html.erb
<h1>Listing anteproyectos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>usuario</th>
      <th>Objetivo</th>
      <th>Justificacion</th>
      <th>Cronograma</th>
      <th>Descripcionactividades</th>
      <th>Nombreemp</th>
      <th>Direccionemp</th>
      <th>Telefonoemp</th>
      <th>Comentarios</th>
      <th>Estatus</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @anteproyectos.each do |anteproyecto| %>
      <tr>
        <td><%= anteproyecto.Nombre %></td>
        <td><%= anteproyecto.user.email %></td>
        <td><%= anteproyecto.Objetivo %></td>
        <td><%= anteproyecto.Justificacion %></td>
        <td><%= anteproyecto.Cronograma %></td>
        <td><%= anteproyecto.DescripcionActividades %></td>
        <td><%= anteproyecto.NombreEmp %></td>
        <td><%= anteproyecto.DireccionEmp %></td>
        <td><%= anteproyecto.TelefonoEmp %></td>
        <td><%= anteproyecto.Comentarios %></td>
        <td><%= anteproyecto.Estatus %></td>
        <td><%= link_to 'Show', anteproyecto %></td>
        <td><%= link_to 'Edit', edit_anteproyecto_path(anteproyecto) %></td>
        <td><%= link_to 'Destroy', anteproyecto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.TipoUsuario == "Alumno" %>
<%= link_to 'New Anteproyecto', new_anteproyecto_path %>
<%end%>

Sigor/app/views/anteproyectos/new.html.erb
<h1>New anteproyecto</h1>

<%= render 'form' %>

<%= link_to 'Back', anteproyectos_path %>

Sigor/app/views/anteproyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @anteproyecto.Nombre %>
</p>

<p>
  <strong>Objetivo:</strong>
  <%= @anteproyecto.Objetivo %>
</p>

<p>
  <strong>Justificacion:</strong>
  <%= @anteproyecto.Justificacion %>
</p>

<p>
  <strong>Cronograma:</strong>
  <%= @anteproyecto.Cronograma %>
</p>

<p>
  <strong>Descripcionactividades:</strong>
  <%= @anteproyecto.DescripcionActividades %>
</p>

<p>
  <strong>Nombreemp:</strong>
  <%= @anteproyecto.NombreEmp %>
</p>

<p>
  <strong>Direccionemp:</strong>
  <%= @anteproyecto.DireccionEmp %>
</p>

<p>
  <strong>Telefonoemp:</strong>
  <%= @anteproyecto.TelefonoEmp %>
</p>

<p>
  <strong>Comentarios:</strong>
  <%= @anteproyecto.Comentarios %>
</p>

<p>
  <strong>Estatus:</strong>
  <%= @anteproyecto.Estatus %>
</p>

<%= link_to 'Edit', edit_anteproyecto_path(@anteproyecto) %> |
<%= link_to 'Back', anteproyectos_path %>

Sigor/app/views/home/index.html.erb
<% if user_signed_in? %>
Estas logeao Como: <strong><%= current_user.TipoUsuario%></strong>.
<%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
<%= link_to "Cerrar Sesion", destroy_user_session_path, method: :get, :class => 'navbar-link'  %>
<% else %>
<a href="/users/sign_in">Login</a>
<a href="/users/sign_up">Sign Up</a>
<% end %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

Sigor/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script type="text/javascript" src="assets/application.js"></script>
  <link rel="stylesheet" type="text/css" href="assets/login.css">
  <title>Sigor</title>


  <%= csrf_meta_tags %>
</head>
<body>



<%= yield %>

</body>
</html>